metacraft-labs/codetracer

src/frontend/lib.nim
i managed to apply it in the wrong place two times. sorry! i can't code.
=> fix: re-apply again my hotfix for the hanging process

src/config/default_config.yaml, src/frontend/styles/subwindow.styl
Minor fix for the checkbox and set the traceSharingEnabled to false
=> fix: Install subwindow checkbox :after element

justfile, src/Tuprules.tup, src/common/config.nim, src/frontend/index.nim, src/frontend/index_config.nim, src/frontend/types.nim, src/frontend/ui/state.nim, src/frontend/ui/status.nim, src/frontend/ui/value.nim, ui-tests/tests/lib/ct_helpers.ts, ui-tests/tests/noir/state.spec.ts, ui-tests/tests/noir/stepping.spec.ts, ui-tests/tests/page_objects/state.ts
@pxor added helpers and frontend support to be able to wait for completed moves and some initial stepping tests.
We are adding some initial state panel tests as well.
There is also a simple tup build fix.
TODO: more work on the stepping/move helpers API in future PR-s
=> e2e tests: work on simple state and stepping tests

.github/FUNDING.yml
Added a funding.yml file that displays our open collective page on the sidebar in the github web interface
=> Add opencollective to funding.yml

src/frontend/utils.nim
=> fix: Editors reopen after component closed out

src/common/paths.nim
experimented with recording rubocop, however not so many optimizatations for now. We do filter out steps to `gems/` now, but more parametrization/fixes are still remaining
=> Fix: experiments, optimizations and refactoring for the ruby recorder

examples/ruby_if_statements/if_statements.rb, examples/ruby_loops/loops.rb, src/db-backend/src/expr_loader.rs, src/frontend/ui/editor.nim
Working on integrating the omniscience with the Ruby language. This branch allows for loops with 'while' and 'until' to be integrated and top-level condition statements to be seen properly
=> Fix: Ruby omniscience

src/ct/online_sharing/download.nim, src/ct/trace/storage_and_import.nim, src/ct/utilities/language_detection.nim
This PR works on fixing remote sharing from other computers as we had some assumptions in the importDbTrace function
And fix the wasm language detection on download
=> fix: Download and import Db trace properly

src/ct/db_backend_record.nim, src/ct/trace/record.nim, src/ct/trace/run.nim, src/ct/utilities/language_detection.nim
cleanup/comment out/remove some debug prints
=> fix `ct run` for now for wasm/rust (but not other wasm langs)

src/ct/cli/interactive_replay.nim
Check out the linked issue for details.
=> Fix interactive replay not quitting cleanly when getting a terminal interrupt

non-nix-build/find_git_hash_from_lockfile.py, non-nix-build/install_nargo.sh, non-nix-build/install_wazero.sh
=> Get commit hashes and repo names from flake.lock

.agents/codebase-insights.txt, .agents/tasks/2025/06/03-1439-feat-add-dap-client, src/tui/src/dap_client.rs, src/tui/src/simple_main.rs
=> Feat add dap client

.agents/tasks/2025/06/04-1729-feat-handle-dap-responses-and-events, src/tui/src/actions.rs, src/tui/src/core.rs, src/tui/src/dap_client.rs, src/tui/src/event.rs, src/tui/src/main.rs, src/tui/src/simple_main.rs
originally in #187 with codex; many of the changes might not be relevant, we mostly want to change simple_tui
=> Feat handle dap responses and events

.agents/tasks/2025/06/04-1802-feat-line-numbers, src/tui/src/simple_main.rs
=> Feat: simple-tui line numbers

.agents/tasks/2025/06/05-1644-fix-send-initialize, .agents/tasks/2025/06/05-1717-fix-send-initialize.txt, src/tui/src/dap_client.rs, src/tui/src/simple_main.rs
=> Fix: simple-tui: send initialize

src/db-backend/src/dap_server.rs, src/db-backend/src/main.rs
- allow `dap_server::run` to accept a mutable `Handler`
- delegate breakpoint registration via `Handler::add_breakpoint`
- construct `Handler` in `main` and pass it to the DAP server
=> Refactor DAP server to use handler

appimage-scripts/build_appimage.sh, flake.lock, flake.nix, nix/packages/default.nix, nix/shells/main.nix
=> feat(cargo-stylus): Add cargo-stylus as a dependency to the ct package

CHANGELOG.md, src/frontend/lib.nim, src/frontend/ui/editor.nim, src/frontend/ui/trace.nim
=> Fix certain tooltips and popups being clipped in the first lines of code

CHANGELOG.md, src/frontend/ui/command.nim, src/frontend/ui/command_interpreter.nim
=> Fix incorrect text highlighting persistance after selecting a file in the global search bar

src/frontend/styles/components/data_tables.styl, src/frontend/styles/components/event_log.styl, src/frontend/styles/components/shared_widgets.styl, src/frontend/ui/event_log.nim, src/frontend/ui/state.nim
Add a message for the state component when no variables are available in the current point of execution.
Fix the event log scroll for DT when the output is too long
=> Fix: Minor issues with State and  Event Log components

src/common/ct_event.nim, src/db-backend/src/dap.rs, src/db-backend/src/handler.rs, src/frontend/dap.nim, src/frontend/event_helpers.nim, src/frontend/middleware.nim, src/frontend/ui/editor.nim, src/frontend/ui/status.nim, src/frontend/ui/trace.nim, src/frontend/ui/value.nim, src/frontend/ui_js.nim, src/frontend/utils.nim
Working on fixing the notifications for the electron client. Currently reaching a compilation error:
```
Error: internal error: genTypeInfo(tyNil)
Traceback from system (most recent call last)
```
=> Notification handling

src/frontend/event_helpers.nim, src/frontend/middleware.nim, src/frontend/ui/calltrace.nim, src/frontend/ui/editor.nim, src/frontend/ui/flow.nim, src/frontend/ui/trace.nim, src/frontend/ui/value.nim, src/frontend/utils.nim
fixing a regression, and fixing #329
=> fix: fix reopening or focusing scratchpad

src/frontend/ui/editor.nim, src/frontend/ui/menu.nim
When using `ct host` and trying to open the context menu in the editor tab the browser context menu also opens. This PR fixes this issue.
=> Fix browser context menu opening in firefox

.agents/codebase-insights.txt, src/backend-manager/src/backend_manager.rs, src/backend-manager/src/dap_parser.rs, src/backend-manager/src/paths.rs
I forgot to handle multiple messages in one buffer for the backend sockets. I added it.
=> fix(backend-manager): fix problem with DAP buffering

.github/workflows/codetracer.yml, CHANGELOG.md, README.md, ci/lint/bash.sh, docs/book/src/installation.md, release_checklist.md, src/ct/version.nim, ui-tests/dotnet_build.sh, ui-tests/flake.nix
> [!CAUTION]
> Merge just before pushing the next release!
=> Next release: add better information about the pre-built binaries and packages we provide

node-packages/package.json, node-packages/yarn-project.nix, node-packages/yarn.lock
tried to improve things with @Madman10K (his initiative)
TODO: problem with building (direnv reload leads to an error)
=> Cleanup packages/dependabot 2: try to remove some unused node packages to prevent dependabot alerts for them
