non-nix-build/install_nargo.sh
src/frontend/lib.nim

* upgrade noir for non-nix build
* fix hanging process in the record dialog: ignore stdio for spawn
the older version of noir was producing more warnings, and probably
this might have led to overfilling the stderr buffer like in this case: https://stackoverflow.com/questions/20792427/why-is-my-node-child-process-that-i-created-via-spawn-hanging/20792428#20792428
the proposed `options.stdio` ignore fix prevents this problem

Fix a hanging record process bug

---

src/frontend/lib.nim

i applied the original fix in a wrong way yesterday, which was leading to an exception whenever running `readProcessOutput`, as it does use the stdio

fix: move the stdio ignoring code to the correct function: the incorrect fix was regressing `ct` generally

---

config/default_config.yaml
src/ct/launch/launch.nim
src/ct/online_sharing/security_upload.nim
src/ct/online_sharing/trace_manager.nim
src/ct/trace/record.nim
src/ct/trace/storage_and_import.nim

* fix: copy default config to `config/` as well TODO in the future: hopefully fix build/usage of config to `src/config`, and cleanup the root `config/
* fix: add a simple password length check to show a custom error, instead of exception
* import toBytes from nim-stew
* add a custom print message for manual `ct download` and `ct upload`(also a warning)
* fix some warnings(removing unused imports; probably we have them from before!)
* make `ct` trace sharing commands honor the `traceSharingEnabled` config flag

fix: small fixes, cleanups and improvements for `ct`/trace sharing

---

release_checklist.md

i am not sure if we are always publishing in opencollective: last time I didn't as it was a small release with mostly one fix

docs: add more details to release checklist(change from monday)

---

examples/ruby_maze_solver/lib/maze_solver/maze.rb

A small change to fix the ruby_maze_solver example.
Now it prints the output on multiple lines.

fix(examples): fix `ruby_maze_solver` now print maze on multiple lines

---

appimage-scripts/build_appimage.sh
appimage-scripts/build_with_nim.sh

TODO: The versions of the ssl package in nixpkgs DO NOT coincide with standard ssl releases.
We should figure out a way to get the correct libraries we need

fix(ssl): Use ssl3 for ct binary

---

.github/dependabot.yml

Some of our workflows are sensitive to security vulnerabilities, so it's good to have dependabot set up to remind us to update these workflows as soon as possible. This config is needed because there are no security notifications about action workflows in the security tab as of now, so this is the only way to get notified about such issues.

Add dependabot config for github action workflows

---

src/small-lang/Cargo.lock
src/small-lang/Cargo.toml
src/small-lang/src/main.rs
src/small-lang/tests/basic.rs

- update small-lang to use runtime_tracing 0.10.0
- adjust sequence value recording for new API
- add integration tests that run the `small-lang` binary
- use a mapping of sample programs to expected outputs
- `cargo test --quiet --offline` in `src/small-lang`
- `cargo test --quiet --offline` in `src/db-backend`
- `cargo clippy --quiet --offline` *(fails: `cargo-clippy` not installed)*

Add tests for small-lang

---

.agents/codebase-insights.txt
src/db-backend/src/expr_loader.rs

- detect Ruby `each` loops by looking at `call` nodes that have a block with method name `each`
- document Ruby loop insight
- add a regression test ensuring `ExprLoader` detects Ruby `each` loops
- `cargo build`
- `cargo test`
- `cargo clippy` *(fails: `cargo-clippy` not installed)*

Implement Ruby each loop detection

---

.agents/tasks/2025/06/06-1326-add-reverse-steps.txt
src/db-backend/src/dap_server.rs

- support `reverseContinue` and `stepBack` requests in the DAP server
- record task details for adding reverse steps

Add reverse steps to DAP server

---

.agents/tasks/2025/06/06-1241-wire-dap.txt
.agents/tasks/2025/06/06-1326-add-reverse-steps.txt
src/db-backend/src/dap_server.rs
src/db-backend/tests/dap_session.rs

- extend the DAP server with a `Handler` for executing backend tasks
- support `setBreakpoints`, `stepIn`, `next`, `stepOut` and `continue` commands
- load trace data on launch so stepping works
- expand DAP session tests with a sample handler and a round‑trip test for `stepIn`

Add basic DAP task dispatch

---

.agents/tasks/2025/06/05-1719-footer-no-select.txt
src/frontend/styles/components/status_bar.styl

Added user-select:none styles for location path, inline status, and ready-status spans so text in the status bar can't be highlighted.
originally #198 with codex

fix: prevent text selection in footer

---

README.md

Current release is broken for MacOS. We need to reenable the button when we do a new release.

hotfix: Disable MacOS image download from README.md

---

ci/deploy/docs.sh

When we merge to main this should deploy our docs to https://metacraft-labs.github.io/codetracer

ci: Deploy docs via Github Pages

---

src/ct/codetracer.nim
src/ct/launch/launch.nim
src/ct/stylus/arb_node_utils.nim
src/frontend/trace_metadata.nim

try to show in a better way the problem if no devnode / no connection for `ct arb explorer`, at least showing the underlying exception
for `ct arb deploy` @zah agreed on no rustup/cargo builtin and shelling out for now, if we have a good error; for now no cargo/rust seems to result in
```
Error: Unhandled exception
codetracer.nim:18        codetracer
launch.nim:148           runInitial
deploy.nim:105           deployStylus
deploy.nim:53            doDebugBuild
osproc.nim:1021          startProcess
osproc.nim:1131          startProcessAuxFork
oserr.nim:95             raiseOSError
Unhandled No such file or directory
Additional info: Could not find command: 'cargo'. OS error: No such file or directory
``` 
which does seem clear to me, maybe we can try to add additional context: in a future …

fix: try to report errors for `ct arb` in a better way

---

src/frontend/index.nim

Fixes codetracer not quitting when clicking on the close button or quitting from the menu

Fix codetracer not quitting on macOS when clicking on the close button

---

appimage-scripts/build_appimage.sh
non-nix-build/build.sh
non-nix-build/build_css.sh
non-nix-build/build_in_simple_env.sh
non-nix-build/build_mac_app.sh
non-nix-build/build_with_nim.sh
non-nix-build/env.sh
non-nix-build/install_nargo.sh
non-nix-build/install_nim_osx.sh
non-nix-build/install_rust.sh
non-nix-build/install_tup.sh
non-nix-build/install_wazero.sh
non-nix-build/setup_node_deps.sh
src/common/config.nim
src/config/default_config.yaml
src/frontend/index.nim
src/frontend/types.nim
src/frontend/ui_js.nim
src/tests/.config.yaml

This PR fixes #80 by adding a `skipInstall` setting to the config file. This setting is used to enable/disable showing the installation menu when launching codetracer for the first time.
An algorithm for finding the desktop file was also added in order to skip installation for our distribution packages, including the nix package.
With this change the install menu will only show up for the AppImage and macOS application bundle, where it will really only show up for the AppImage if the AppImage is not distributed as a package by a third-party distribution already, because our packages automatically install the resource files in the required directories.
Tested on:
1. Linux
- With tup
- With nix
- With the AppImage
1. macOS

Only show the install menu outside of local builds/packages

---

.github/workflows/codetracer.yml
README.md
nix/shells/ci.nix
release_checklist.md

This PR does the following:
1. Fixes a number of bugs with our conditions
1. Now pushes a `latest` version of the codetracer appimage and dmg when a release is ready, circumventing the need for manual version changes
1. The dmg and appimage are signed with our organisation's pgp key

Improve the release workflow

---

.gitignore
ci/deploy/docs.sh

This scirpt would fail if the worktree or the branch already exists in the local git copy. We check for those cases and we remove the worktree  after we are finished. Hopefully the CI will become more stable with this change.

ci: Make depoy/docs.sh more robust

---

ci/deploy/docs.sh

The CI requires that commits are GPG signed, which breaks the deploy/docs.sh script. We've added an argument which should fix this.
Here's a script which reproduces the issue locally:
```sh
#!/usr/bin/env bash
set -e # Exit immediately if a command exits with a non-zero status.
echo "--- Starting GPG error reproduction script ---"
if [ ! -f ".git/config" ]; then
echo "ERROR: This script must be run from the root of the repository."
exit 1
fi
if [ ! -d "docs/book" ]; then
echo "ERROR: The 'docs/book' directory does not exist."
exit 1
fi
pushd docs/book/ > /dev/null
original_gpgsign=$(git config --get commit.gpgsign || true)
original_signingkey=$(git config --get user.signingkey || true)
cleanup() {
echo "--- Cleaning up ---"
if [[ "$(basename "$PWD")" == "gh-pages" ]]; then
cd ..
fi
if [ …
```

ci/deploy/docs.sh: Fix GPG signing issue during CI

---

src/db-backend/src/dap.rs
src/db-backend/src/dap_server.rs
src/db-backend/src/event_db.rs
src/db-backend/src/handler.rs
src/frontend/types.nim
src/frontend/ui/calltrace.nim
src/frontend/ui/state.nim
src/frontend/ui/terminal_output.nim
src/frontend/ui/value.nim

Things that are fixed for the dap support and extension support:
- Value history and value history jump
- Value history scroll position and onWheel event listener
- Event log redraw on start when CtUpdatedEvents has been received
- Add terminal jump and initialUpdate on CtUpdatedEvents for the terminal output component
- Add support for vscode "restart" message so it doesn't hang
- Fix calltrace search handling and call jump from the results

feat: Stabilize extension components

---

appimage-scripts/build_with_nim.sh
flake.lock
nix/packages/default.nix
nix/shells/main.nix
src/db-backend/Cargo.lock
src/db-backend/Cargo.toml
src/db-backend/src/handler.rs
src/db-backend/src/trace_processor.rs

This brings support for the new "version 1" of the binary trace format, which is based on CBOR + Zstd compression. All the previous formats (binary "version 0", based on capnproto, and the JSON format) are still supported and should continue to work seamlessly. In the case of binary, the exact version of the format is detected from the file header.

feat: binary trace format "version 1", based on CBOR and Zstd seekable compression

---

src/common/ct_event.nim
src/frontend/dap.nim
src/frontend/event_helpers.nim
src/frontend/middleware.nim
src/frontend/types.nim
src/frontend/ui/calltrace.nim
src/frontend/ui/flow.nim
src/frontend/ui/scratchpad.nim
src/frontend/ui/show_code.nim
src/frontend/ui/value.nim
src/frontend/ui_js.nim

- Fix minor issue with building for extension
- Fix mutation observer for calltrace #322 
- Fix scratchpad redraw issues #323
- Double component registration issue which might have been the issue with the slow golden layout movements #324 (more testing needs to be done on the matter)

Fix: Regressions for electron client after DAP integration

---

.gitmodules
docs/book/src/misc/environment_variables.md
nim.cfg
src/ct/db_backend_record.nim

Nikola proposed putting something like guid-s/uuid-s here, 
first we tried with`oid`, it is taken from nim stdlib `std/oids`: not sure if good enough for this case
it seems it wasn't maybe sure enough, so tried a library: hopefully this is valid uuid v4: 
https://github.com/vtbassmatt/nim-uuid4 credits to Matt Cooper its author
one case when this should work is when `CODETRACER_SHELL_EXPORT` is set to a non-empty folder name (of the target trace archives folder)

fix: try to generate a more unique id in the trace archive filename when export folder is set

---

src/ct/launch/launch.nim
src/ct/trace/storage_and_import.nim
src/ct/utilities/git.nim
src/frontend/index_config.nim

this fixes a bit of the filesystem panel: now showing `main.nr` again for something like `ct record /tmp/noir_test`, but still not Nargo.toml and others their logic seems more connected to the repo case? not sure when or if fix
use `Result` instead of "" for no git root
originally bug from Nikola for importing/patching such a trace

fix: fix a bug in `ct record`: store sensible source folders if not git repo

---

src/ct/online_sharing/download.nim
src/ct/online_sharing/online_sharing_test.nim
src/ct/online_sharing/upload.nim
src/ct/trace/replay.nim
src/ct/trace/shell.nim
src/ct/trace/storage_and_import.nim
src/ct/utilities/language_detection.nim

make it possible to use `ct replay -t=<directly-created-by-recorder-trace>`

Feat: autoimport traces in replay: pass raw traces directly to `ct replay -t=..`

---

non-nix-build/build_mac_app.sh
resources/Info.plist

Currently we're not synchronising versions between `version.nim` and `Info.plist`. This patch replaces with the correct version on each build.

Synchronise the version in version.nim with the version in Info.plist

---

src/backend-manager/Cargo.lock
src/ct/trace/multitrace.nim
src/tui/Cargo.lock
src/tui/Cargo.toml
test-programs/stylus_fund_tracker/Cargo.toml
test-programs/stylus_fund_tracker/src/lib.rs

Should fix the following dependabot alerts:
#250 
#246
#245
#239 
#236 
#221

Resolve security vulnerabilities in some rust dependencies
